#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-minitest-autotest
Version  : 1.0.1
Release  : 5
URL      : https://rubygems.org/downloads/minitest-autotest-1.0.1.gem
Source0  : https://rubygems.org/downloads/minitest-autotest-1.0.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-minitest-autotest-bin
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
= minitest-autotest
home :: https://github.com/seattlerb/minitest-autotest
rdoc :: http://docs.seattlerb.org/minitest-autotest

%package bin
Summary: bin components for the rubygem-minitest-autotest package.
Group: Binaries

%description bin
bin components for the rubygem-minitest-autotest package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n minitest-autotest-1.0.1
gem spec %{SOURCE0} -l --ruby > rubygem-minitest-autotest.gemspec

%build
gem build rubygem-minitest-autotest.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
minitest-autotest-1.0.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/minitest-autotest-1.0.1 && rake --trace test TESTOPTS="-v" && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/minitest-autotest-1.0.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/AutoUpdate/cdesc-AutoUpdate.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/AutoUpdate/sleep_time%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/AutoUpdate/update_cmd%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Bundler/cdesc-Bundler.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Fixtures/cdesc-Fixtures.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Isolate/cdesc-Isolate.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Isolate/dir%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Migrate/cdesc-Migrate.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Once/cdesc-Once.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Preload/cdesc-Preload.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Preload/glob%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Preload/glob-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/RCov/cdesc-RCov.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/RCov/command%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/RCov/options%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/RCov/pattern%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Restart/cdesc-Restart.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/Timestamp/cdesc-Timestamp.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/add_exception-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/add_hook-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/add_mapping-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/add_sigint_handler-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/add_sigquit_handler-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/all_good-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/cdesc-Autotest.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/class_map-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/clear_exceptions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/clear_mappings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/debug-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/exceptions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/extra_class_map-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/extra_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/failures-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/files_matching-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/files_to_test-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/find_directories-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/find_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/find_files_to_test-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/find_order-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/get_to_green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/hook-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/interrupted-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/known_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/last_mtime-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/libs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/make_test_cmd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/minitest_result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/minitest_start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/new_hash_of_arrays-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/old_path_to_classname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/old_run_tests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/parse_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/path_to_classname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/prefix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/remove_exception-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/remove_mapping-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/reorder-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/rerun_all_tests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/reset_find_order-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/restart-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/ruby-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/ruby_cmd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/run-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/run_tests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/sleep-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/tainted%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/tainted-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/test_files_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/test_mappings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/test_prefix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/testlib-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/wait_for_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Autotest/wants_to_quit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Minitest/Autotest/cdesc-Autotest.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/Minitest/cdesc-Minitest.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/page-History_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest-autotest-1.0.1/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/.autotest
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/.gemtest
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/History.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/bin/autotest
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest/autoupdate.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest/bundler.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest/fixtures.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest/isolate.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest/migrate.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest/once.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest/preload.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest/rails.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest/rcov.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest/restart.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest/timestamp.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/minitest/autotest.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/test/test_minitest/test_autorun.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/test/test_minitest/test_good.rb
/usr/lib64/ruby/gems/2.2.0/specifications/minitest-autotest-1.0.1.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/autotest
